<?php

namespace Database\Seeders;

use App\Models\DatosPreoperacional;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatosPreoperacionalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DatosPreoperacional::create([
            'cedula' => '1104127568',
            'nombre_completo' => 'ADOLFO PEÑA DIAZ',
            'correo' => 'adolfo.pena@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'NKM95D',
            'modelo' => '2015',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095823684',
            'nombre_completo' => 'ANDRES FELIPE GUEVARA CACERES',
            'correo' => 'andres.guevara@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'MXQ16C',
            'modelo' => '2012',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098807358',
            'nombre_completo' => 'ANDRES FELIPE LOPEZ GOMEZ',
            'correo' => 'andres.lopez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'YMI89F',
            'modelo' => '2022',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1099372420',
            'nombre_completo' => 'ANDREW JOSEPT SANCHEZ RODRIGUEZ',
            'correo' => 'andrew.sanchez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'RIL08C',
            'modelo' => '2012',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095944538',
            'nombre_completo' => 'BRAYAN EFRAIN DUARTE ARDILA',
            'correo' => 'brayan.duarte@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'NJR16E',
            'modelo' => '2018',
            'cargo' => 'COORDINADOR DE INVESTIGACION Y SUSPENSIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1005303952',
            'nombre_completo' => 'CARLOS CORTES ARIZA',
            'correo' => 'carlos.cortes@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'PUO03A',
            'modelo' => '2015',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098666800',
            'nombre_completo' => 'CARLOS ENRIQUE MONTAÑEZ SUAREZ',
            'correo' => 'carlos.montanez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'HII42C',
            'modelo' => '2011',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1096513989',
            'nombre_completo' => 'CAROLINA OCHOA AVENDAÑO',
            'correo' => 'carolina.ochoa@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'HUG98D',
            'modelo' => '2017',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102375737',
            'nombre_completo' => 'CESAR DAVID CAMACHO JEREZ',
            'correo' => 'cesar.camacho@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BZX58E',
            'modelo' => '2018',
            'cargo' => 'AUXILIAR DE INVESTIGACION Y PERDIDAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1096195256',
            'nombre_completo' => 'CINDY LISETH HERNANDEZ QUINTERO',
            'correo' => 'cindy.hernandez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'HTT02B',
            'modelo' => '2008',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100959362',
            'nombre_completo' => 'CRISTIAN FERNANDO MUÑOZ DURAN',
            'correo' => 'cristian.munoz@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL  ',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'LKL26E',
            'modelo' => '2019',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095907374',
            'nombre_completo' => 'CRISTIAN SEBASTIAN CALDERON CASTILLO',
            'correo' => 'cristian.calderon@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'LHO64D',
            'modelo' => '2014',
            'cargo' => 'COORDINADOR DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102371222',
            'nombre_completo' => 'CRISTIAN YESID PEREZ MANTILLA',
            'correo' => 'cristian.mantilla@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'PGD13D',
            'modelo' => '2015',
            'cargo' => 'TECNICO CARTOGRAFICO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1097990947',
            'nombre_completo' => 'DAVID ALONSO MONCADA OLAYA',
            'correo' => 'david.moncada@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'SAF76C',
            'modelo' => '2013',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091652668',
            'nombre_completo' => 'DAVID CONTRERAS GONZALEZ',
            'correo' => 'david.contreras@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'YMM07C',
            'modelo' => '2013',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '18955197',
            'nombre_completo' => 'DEIBER ORLANDO VEGA ALVARAN',
            'correo' => 'deiber.vega@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA ',
            'placa_vehiculo' => 'PYR91E',
            'modelo' => '2018',
            'cargo' => 'TECNICO DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098604385',
            'nombre_completo' => 'DIEGO ALFONSO LAGUADO CASTRO',
            'correo' => 'diego.laguado@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'TAW87F',
            'modelo' => '2022',
            'cargo' => 'COORDINADOR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13176435',
            'nombre_completo' => 'DIEGO ARMANDO ANGARITA ROPERO',
            'correo' => 'diego.angarita@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'QBQ11B',
            'modelo' => '2009',
            'cargo' => 'COORDINADOR TELEMETRIA Y GNC',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095794538',
            'nombre_completo' => 'DIEGO ARMANDO SANDOVAL GUALDRON',
            'correo' => 'diego.sandoval@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'QAL82C',
            'modelo' => '2012',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091676079',
            'nombre_completo' => 'DUBAN  QUINTERO LAZARO',
            'correo' => 'duban.quintero@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'DQK44F',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1004945121',
            'nombre_completo' => 'DUVAN FELIPE SANCHEZ ARMESTO',
            'correo' => 'duvan.sanchez@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'FBU84F',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095923725',
            'nombre_completo' => 'EDUARD AUGUSTO ALMEIDA MOTTA',
            'correo' => 'eduard.almeida@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'PGW71D',
            'modelo' => '2015',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095829487',
            'nombre_completo' => 'EDWIN DIAZ ACEVEDO',
            'correo' => 'edwin.diaz@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'SAF42C',
            'modelo' => '2013',
            'cargo' => 'TECNICO DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098721221',
            'nombre_completo' => 'ELKIN DARIO GOMEZ NIÑO',
            'correo' => 'elkin.gomez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'CBB05D',
            'modelo' => '2014',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1101154197',
            'nombre_completo' => 'ELKIN URBANO RUEDA LANDINEZ',
            'correo' => 'elkin.rueda@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'HGJ09F',
            'modelo' => '2021',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13718949',
            'nombre_completo' => 'EMERSON JULIAN BECERRA MANOSALVA',
            'correo' => 'emerson.becerra@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'UJX06E',
            'modelo' => '2019',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91512021',
            'nombre_completo' => 'EUSEBIO  ESPARZA PEÑARANDA',
            'correo' => 'eusebio.esparza@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'VEY53F',
            'modelo' => '2022',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098669102',
            'nombre_completo' => 'FABIAN ANDRES AVENDAÑO PRADO',
            'correo' => 'fabian.avendano@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'KPB24E',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1099373052',
            'nombre_completo' => 'FABIAN ANDRES GUARIN CABALLERO',
            'correo' => 'fabian.guarin@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'LSY98E',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102361011',
            'nombre_completo' => 'FABIO ALONSO CASTELLANOS GALVIS',
            'correo' => 'fabio.castellanos@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'MXC05C',
            'modelo' => '2012',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91356744',
            'nombre_completo' => 'FAVIO VEGA MESA',
            'correo' => 'favio.vega@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'PGJ91D',
            'modelo' => '2016',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098764839',
            'nombre_completo' => 'FAYBER EDUARDO BARAJAS PUENTES',
            'correo' => 'fayber.barajas@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'RBE79B',
            'modelo' => '2010',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102368960',
            'nombre_completo' => 'FIDEL ALEXANDER HERNANDEZ RUIZ',
            'correo' => 'fidel.hernandez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'XNW17E',
            'modelo' => '2019',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100956456',
            'nombre_completo' => 'FREDY  MAURICIO PATIÑO GELVEZ',
            'correo' => 'fredy.gelvez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'LAW08D',
            'modelo' => '2015',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100957594',
            'nombre_completo' => 'FREDY ALEXANDER ALBORNOZ AYALA',
            'correo' => 'fredy.albornoz@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'XGO47E',
            'modelo' => '2019',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098610278',
            'nombre_completo' => 'GABRIEL HERNANDO CASTRO ESCOBAR( CARRO PARTICULAR, VA EN PREOPERACIONAL DE MOTOS ',
            'correo' => 'gabriel.castro@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'GZP450',
            'modelo' => '2021',
            'cargo' => 'COORDINADOR DE REPARACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098676448',
            'nombre_completo' => 'GIOVANNY ORTIZ VERA ',
            'correo' => 'giovanny.ortiz@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BQN55D',
            'modelo' => '2014',
            'cargo' => 'TECNICO DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100958711',
            'nombre_completo' => 'GLORIA VANESSA QUINTERO SOLANO',
            'correo' => 'gloria.quintero@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'AOJ42B',
            'modelo' => '2006',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091656253',
            'nombre_completo' => 'HAROLD ANDREY SEPULVEDA AMAYA',
            'correo' => 'harold.sepulveda@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'XOP73F',
            'modelo' => '2022',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095808214',
            'nombre_completo' => 'HEIBER FABIAN MORENO AYALA',
            'correo' => 'heiber.moreno@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'DXG68D',
            'modelo' => '2014',
            'cargo' => 'AUXILIAR DE INVESTIGACION Y PERDIDAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13715418',
            'nombre_completo' => 'HENRY  LARROTTA DUARTE',
            'correo' => 'henry.larrota@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'THJ67D',
            'modelo' => '2017',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098676584',
            'nombre_completo' => 'IVAN ESTRADA PABON',
            'correo' => 'ivan.estrada@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'CARTERA',
            'placa_vehiculo' => 'NIS88E',
            'modelo' => '2018',
            'cargo' => 'GESTOR CARTERA',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1099874652',
            'nombre_completo' => 'IVAN FERNEY PICO CASTRO',
            'correo' => 'ivan.pico@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'PYV54E',
            'modelo' => '2018',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1097970420',
            'nombre_completo' => 'IVAN RICARDO CASTRO DELGADILLO',
            'correo' => 'ivan.castro@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BVS22F',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91538832',
            'nombre_completo' => 'JAVIER  LOZANO RODRIGUEZ',
            'correo' => 'javier.lozano@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'TFX33D',
            'modelo' => '2016',
            'cargo' => 'COORDINADOR DE METROLOGIA',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1068953105',
            'nombre_completo' => 'JHERSSON JAIR FRESNEDA RODRIGUEZ',
            'correo' => 'jhersson.fresneda@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'ZTR36C',
            'modelo' => '2014',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1004899129',
            'nombre_completo' => 'JHON EDINSON BARBOSA SANCHEZ',
            'correo' => 'jhon.barbosa@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'KAB32D',
            'modelo' => '2016',
            'cargo' => 'AUXILIAR DE INVESTIGACION Y PERDIDAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '14606583',
            'nombre_completo' => 'JOHAN MARINO PALACIOS CORTES',
            'correo' => 'johan.marino@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'TGA46D',
            'modelo' => '2016',
            'cargo' => 'TECNICO DE REDES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091672328',
            'nombre_completo' => 'JOHAN YESID PEREZ ORTEGA',
            'correo' => 'johan.perez@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'WOA64C',
            'modelo' => '2012',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091595048',
            'nombre_completo' => 'JOHNFREY  PEREZ GARCIA',
            'correo' => 'jhonfrey.perez@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'UNE57F',
            'modelo' => '2022',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13718284',
            'nombre_completo' => 'JORGE ALEXANDER HERNANDEZ HALLADO',
            'correo' => 'jorge.hernandez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'RAU69B',
            'modelo' => '2010',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098409254',
            'nombre_completo' => 'JORGE IVAN RODRIGUEZ CAMACHO',
            'correo' => 'jorge.rodriguez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'LTC54E',
            'modelo' => '2021',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91537137',
            'nombre_completo' => 'JORGE IVAN TORRES MEJIA',
            'correo' => 'jorge.torres@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'MBJ21B',
            'modelo' => '2009',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91270679',
            'nombre_completo' => 'JOSE LUIS JAIMES GUTIERREZ',
            'correo' => 'jose.jaimes@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'JSL48F',
            'modelo' => '2020',
            'cargo' => 'JEFE DE VENTAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1005149252',
            'nombre_completo' => 'JUAN CAMILO CABALLERO GARCIA',
            'correo' => 'juan.caballero@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'XNG 43C',
            'modelo' => '2013',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '2159067',
            'nombre_completo' => 'JUAN CARLOS ANAYA OVIEDO',
            'correo' => 'juan.anaya@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'OJF26C',
            'modelo' => '2012',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100969235',
            'nombre_completo' => 'JUDITH KATHERINE AMADO RUIZ',
            'correo' => 'judith.amado@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'LSF69E',
            'modelo' => '2018',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098815848',
            'nombre_completo' => 'JULIAN ALONSO GALVIS CASTAÑEDA',
            'correo' => 'julian.galvis@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'BHO86D',
            'modelo' => '2014',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098722908',
            'nombre_completo' => 'LUIS ALBERTO NAVARRO CACUA',
            'correo' => 'alberto.navarro@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'YEU83D',
            'modelo' => '2016',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098686311',
            'nombre_completo' => 'LUIS EDUARDO GOMEZ GIL',
            'correo' => 'eduardo.gil@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'TOQ16C',
            'modelo' => '2012',
            'cargo' => 'COORDINADOR DE SERVICIOS Y REPARACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91218443',
            'nombre_completo' => 'LUIS EDUARDO ORTEGA ',
            'correo' => 'luis.ortega@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'HIW93C',
            'modelo' => '2012',
            'cargo' => 'COORDINADOR DE REDES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13177685',
            'nombre_completo' => 'LUIS JOSE NAVARRO CASTILLA',
            'correo' => 'luis.navarro@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'AVC61C ',
            'modelo' => '2010',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91349901',
            'nombre_completo' => 'MARCO ANTONIO MORENO RAMIREZ',
            'correo' => 'marco.moreno@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'MAX17B',
            'modelo' => '2008',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098386168',
            'nombre_completo' => 'MARINELA TERESA AMAYA CALDERON',
            'correo' => 'marinela.amaya@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'CARTERA',
            'placa_vehiculo' => 'GOL50C',
            'modelo' => '2013',
            'cargo' => 'GESTOR CARTERA',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098639560',
            'nombre_completo' => 'MARTHA CRISTINA CLAVIJO VARGAS',
            'correo' => 'martha.clavijo@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'CARTERA',
            'placa_vehiculo' => 'XOO67F',
            'modelo' => '2022',
            'cargo' => 'GESTOR CARTERA',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091653038',
            'nombre_completo' => 'MAURICIO SANJUAN GARCIA',
            'correo' => 'mauricio.sanjuan@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'AUZ55C',
            'modelo' => '2010',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1007693905',
            'nombre_completo' => 'MIGUEL ANGEL ROJAS APARICIO',
            'correo' => 'miguel.rojas@metrogassaesp.com',
            'lugar_trabajo' => 'SOCORRO',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BVP58F',
            'modelo' => '2020',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091653970',
            'nombre_completo' => 'NANDY MILENA PACHECO CARRASCAL',
            'correo' => 'nandy.pacheco@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'CARTERA',
            'placa_vehiculo' => 'SSZ89D',
            'modelo' => '2015',
            'cargo' => 'GESTOR CARTERA',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91259334',
            'nombre_completo' => 'NELSON  ESPINOSA CHAPARRO',
            'correo' => 'nelson.espinosa@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'UPH73C',
            'modelo' => '2013',
            'cargo' => 'COORDINADOR DE REPARACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098657559',
            'nombre_completo' => 'NELSON ENRIQUE PUENTES LIPEZ',
            'correo' => 'nelson.lopez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BRT99D',
            'modelo' => '2014',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098621623',
            'nombre_completo' => 'NESTOR JAVIER VILLABONA ALMEYDA',
            'correo' => 'nestor.villabona@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'EMW21F',
            'modelo' => '2020',
            'cargo' => 'TECNICO DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '37900018',
            'nombre_completo' => 'NINI JOHANA ANGULO BENAVIDES',
            'correo' => 'nini.angulo@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'GNV56C',
            'modelo' => '2012',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095841077',
            'nombre_completo' => 'OMAR DAVID RODRIGUEZ GONZALEZ',
            'correo' => 'omar.rodriguez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'ZJE01C',
            'modelo' => '2013',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100958973',
            'nombre_completo' => 'OMAR VICENTE PORRAS ZULETA',
            'correo' => 'omar.porras@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'SBE11D',
            'modelo' => '2015',
            'cargo' => 'COORDINADOR DE INSTALACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091672289',
            'nombre_completo' => 'OSNAIDER GUERRERO YAÑEZ',
            'correo' => 'osnaider.guerrero@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'SLV48C',
            'modelo' => '2013',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13540149',
            'nombre_completo' => 'PABLO  EDUARDO ARDILA TORRES',
            'correo' => 'pablo.ardila@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'FGQ44E',
            'modelo' => '2017',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '13177774',
            'nombre_completo' => 'PAUL BREINER PINO FEREZ',
            'correo' => 'paul.pino@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'WGQ15A',
            'modelo' => '2007',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102383338',
            'nombre_completo' => 'RAFAEL EDUARDO RINCON PEÑA',
            'correo' => 'rafael.rincon@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'HET23F',
            'modelo' => '2022',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '79836728',
            'nombre_completo' => 'RAMIRO CLAVIJO CABALLERO',
            'correo' => 'ramiro.clavijo@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'HZO27',
            'modelo' => '2003',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098682970',
            'nombre_completo' => 'SAMIL JULIAN BENITEZ CELIS',
            'correo' => 'samil.benitez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'GAF72F',
            'modelo' => '2021',
            'cargo' => 'TECNICO DE EMERGENCIAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095824782',
            'nombre_completo' => 'SERGIO ALEXANDER REYES ESPINOSA',
            'correo' => 'sergio.reyes@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'BJK06D',
            'modelo' => '2016',
            'cargo' => 'AUXILIAR DE MANTENIMIENTO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1064838575',
            'nombre_completo' => 'SERGIO ARMANDO PEÑARANDA MARTINEZ',
            'correo' => 'sergio.penaranda@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'IRA83F',
            'modelo' => '2021',
            'cargo' => 'COORDINADOR DE INSTALACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095806511',
            'nombre_completo' => 'WILLIAM GERARDO ROJAS SUAREZ',
            'correo' => 'william.rojas@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'SAK95C',
            'modelo' => '2013',
            'cargo' => 'COORDINADOR DE INSTALACIONES',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1095811014',
            'nombre_completo' => 'WILMER ANDRES NIÑO SALAZAR ',
            'correo' => 'wilmer.nino@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'GAC27D',
            'modelo' => '2013',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102362598',
            'nombre_completo' => 'WILMER AUGUSTO BARRETO ALBARRACIN',
            'correo' => 'wilmer.barreto@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'POH45F',
            'modelo' => '2021',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1063617505',
            'nombre_completo' => 'WILVER ARMESTO GAMBOA',
            'correo' => 'wilver.armesto@metrogassaesp.com',
            'lugar_trabajo' => 'RIO DE ORO',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'KUH91E',
            'modelo' => '2018',
            'cargo' => 'SUPERVISOR CENTROS POBLADOS RIO DE ORO',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091675175',
            'nombre_completo' => 'YAN CARLOS QUINTANA AREVALO',
            'correo' => 'yan.quintana@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'UNE94F',
            'modelo' => '2022',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '5470893',
            'nombre_completo' => 'YANY JOSE QUINTERO AMAYA',
            'correo' => 'yany.quintero@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'QYM88E',
            'modelo' => '2019',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100948537',
            'nombre_completo' => 'YARI ZULAY DIAZ ARIAS',
            'correo' => 'yari.diaz@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'LDT51C',
            'modelo' => '2011',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '91514075',
            'nombre_completo' => 'YESID FERNANDO GOMEZ GOMEZ',
            'correo' => 'yesid.gomez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'VGR53F',
            'modelo' => '2022',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091662504',
            'nombre_completo' => 'YILVER OSBALDO BALLESTEROS CARDENAS',
            'correo' => 'yilver.ballesteros@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'UPG40C',
            'modelo' => '2013',
            'cargo' => 'TECNICO INSTALADOR',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1091671487',
            'nombre_completo' => 'YORLANDY PEREZ PRADA',
            'correo' => 'yorlandy.perez@metrogasaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'JXP85E',
            'modelo' => '2017',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1064840143',
            'nombre_completo' => 'YUSLEIBY CATHERINE DURAN AREVALO',
            'correo' => 'yusleiby.duran@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'LPZ84D',
            'modelo' => '2015',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1100960446',
            'nombre_completo' => 'MARIA FERNANDA GOMEZ RUIZ',
            'correo' => 'fernanda.gomez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'YEQ47D',
            'modelo' => '2016',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1104125792',
            'nombre_completo' => 'RONALD RENE BASTIDAS RINCON',
            'correo' => 'ronald.bastidas@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'TECNICA',
            'placa_vehiculo' => 'HGI05G',
            'modelo' => '2023',
            'cargo' => 'AUXILIAR DE INVESTIGACION Y PERDIDAS',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '77132583',
            'nombre_completo' => 'HENRY HERRERA RODRIGUEZ',
            'correo' => 'henry.herrera@metrogassaesp.com',
            'lugar_trabajo' => 'OCAÑA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'LDG27C',
            'modelo' => '2011',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1102379608',
            'nombre_completo' => 'CARLOS FERNANDO ORDUZ GOMEZ',
            'correo' => 'carlos.orduz@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'VWG86C',
            'modelo' => '2012',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1098643425',
            'nombre_completo' => 'LEIDY ROCIO GELVEZ JURADO',
            'correo' => 'leidy.gelvez@metrogassaesp.com',
            'lugar_trabajo' => 'SAN GIL',
            'area' => 'COMERCIAL',
            'placa_vehiculo' => 'FUU38E',
            'modelo' => '2016',
            'cargo' => 'ASESOR COMERCIAL',
            'tipo_vehiculo' => '1',
        ]);
        DatosPreoperacional::create([
            'cedula' => '1005163212',
            'nombre_completo' => 'CESAR LUIS FLOREZ CONTRERAS',
            'correo' => 'cesar.florez@metrogassaesp.com',
            'lugar_trabajo' => 'FLORIDABLANCA',
            'area' => 'FACTURACION',
            'placa_vehiculo' => 'BZG94F',
            'modelo' => '2020',
            'cargo' => 'AUXILIAR DE FACTURACION',
            'tipo_vehiculo' => '1',
        ]);
    }
}
